# Generated by Django 6.0.1 on 2026-01-19 12:15

import django.core.validators
import django.db.models.deletion
import uuid
import videos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name without the # symbol', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this tag represents')),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for the tag badge', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tag is available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Tag',
                'verbose_name_plural': 'Video Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)])),
                ('description', models.TextField(blank=True, help_text='Video description (max 5000 characters)', max_length=5000, validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('video_file', models.FileField(help_text='Supported formats: MP4, WebM, MOV, AVI, MKV. Max size: 500MB', upload_to=videos.models.video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'avi', 'mkv']), videos.models.validate_video_file_size])),
                ('cover_image', models.ImageField(help_text='Cover image for the video. Supported formats: JPG, PNG, WebP. Max size: 5MB', upload_to=videos.models.cover_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), videos.models.validate_cover_file_size])),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('unique_view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('dislike_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this video is visible to users')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured videos appear at the top')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, help_text='Maximum 50 tags per video', related_name='videos', to='videos.videotag')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='For anonymous view tracking', null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_views', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='videos.video')),
            ],
            options={
                'verbose_name': 'Video View',
                'verbose_name_plural': 'Video Views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment text (max 2000 characters)', max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this comment is visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment for replies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='videos.videocomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_comments', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videos.video')),
            ],
            options={
                'verbose_name': 'Video Comment',
                'verbose_name_plural': 'Video Comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['video', '-created_at'], name='videos_vide_video_i_947613_idx'), models.Index(fields=['user', '-created_at'], name='videos_vide_user_id_f8e42e_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_reactions', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='videos.video')),
            ],
            options={
                'verbose_name': 'Video Reaction',
                'verbose_name_plural': 'Video Reactions',
                'ordering': ['-created_at'],
                'unique_together': {('video', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-created_at'], name='videos_vide_created_1f1e45_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_active', '-created_at'], name='videos_vide_is_acti_834e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_featured', '-created_at'], name='videos_vide_is_feat_3c2629_idx'),
        ),
        migrations.AddIndex(
            model_name='videoview',
            index=models.Index(fields=['video', '-viewed_at'], name='videos_vide_video_i_b6d345_idx'),
        ),
        migrations.AddIndex(
            model_name='videoview',
            index=models.Index(fields=['user', 'video'], name='videos_vide_user_id_0e14b6_idx'),
        ),
    ]
