# Generated by Django 6.0.1 on 2026-01-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Profile name, e.g., 'Gaming Content', 'Nature Videos'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this tag profile')),
                ('color', models.CharField(default='#8B5CF6', help_text='Hex color code for the profile badge', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this profile is available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(help_text='Tags included in this profile', related_name='profiles', to='videos.videotag')),
            ],
            options={
                'verbose_name': 'Tag Profile',
                'verbose_name_plural': 'Tag Profiles',
                'ordering': ['name'],
            },
        ),
    ]
