# Generated by Django 6.0.1 on 2026-01-19 13:03

import django.core.validators
import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_tagprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='embed_url',
            field=models.URLField(blank=True, help_text='YouTube, Twitch, or Kick video URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_source',
            field=models.CharField(choices=[('upload', 'Uploaded File'), ('youtube', 'YouTube'), ('twitch', 'Twitch'), ('kick', 'Kick')], default='upload', help_text='Source of the video', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image for the video. Supported formats: JPG, PNG, WebP. Max size: 5MB', null=True, upload_to=videos.models.cover_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), videos.models.validate_cover_file_size]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Supported formats: MP4, WebM, MOV, AVI, MKV. Max size: 500MB', null=True, upload_to=videos.models.video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'avi', 'mkv']), videos.models.validate_video_file_size]),
        ),
    ]
