# Generated by Django 6.0.1 on 2026-01-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_game_type'),
        ('users', '0002_add_mfa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_games',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='core.game'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
