# Generated by Django 6.0.1 on 2026-01-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_privatemessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='privatemessage',
            new_name='users_priva_sender__ccf1b3_idx',
            old_name='users_priva_sender__idx',
        ),
        migrations.RenameIndex(
            model_name='privatemessage',
            new_name='users_priva_recipie_57c9d3_idx',
            old_name='users_priva_recipie_idx',
        ),
        migrations.AddField(
            model_name='customuser',
            name='discord_url',
            field=models.URLField(blank=True, help_text='Discord profile or server URL', max_length=500, null=True),
        ),
    ]
