# Generated by Django 6.0.1 on 2026-01-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_users_priva_sender__idx_users_priva_sender__ccf1b3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kick_url',
            field=models.URLField(blank=True, help_text='Kick channel URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stream_url',
            field=models.URLField(blank=True, help_text='Twitch stream URL', max_length=500, null=True),
        ),
    ]
