# Generated by Django 6.0.1 on 2026-01-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_profile_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorite_games',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_games',
            field=models.JSONField(blank=True, default=list, help_text='List of favorite game names as tags'),
        ),
    ]
