# Generated by Django 6.0.1 on 2026-01-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_change_favorite_games_to_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_streamer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stream_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
