# Generated by Django 6.0.1 on 2026-01-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_streamer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='banned_until',
            field=models.DateTimeField(blank=True, help_text='User is banned until this date', null=True),
        ),
    ]
