from django.core.management.base import BaseCommand
from core.models import Game, GameSettingDefinition


class Command(BaseCommand):
    help = 'Seeds complete game setting definitions for Call of Duty, Battlefield, and Arc Raiders'

    def handle(self, *args, **options):
        # ============================================================
        # CALL OF DUTY: WARZONE / MW3 - Complete Graphics Settings
        # ============================================================
        cod_settings = [
            # === DISPLAY TAB ===
            {'name': 'display_mode', 'display_name': 'Display Mode', 'field_type': 'select', 'category': 'display',
             'options': ['Fullscreen Exclusive', 'Fullscreen Borderless', 'Windowed'], 'default_value': 'Fullscreen Exclusive', 'order': 1},
            {'name': 'display_monitor', 'display_name': 'Display Monitor', 'field_type': 'select', 'category': 'display',
             'options': ['Monitor 1', 'Monitor 2', 'Monitor 3'], 'default_value': 'Monitor 1', 'order': 2},
            {'name': 'display_adapter', 'display_name': 'Display Adapter', 'field_type': 'select', 'category': 'display',
             'options': ['Auto Detect', 'GPU 1', 'GPU 2'], 'default_value': 'Auto Detect', 'order': 3},
            {'name': 'screen_refresh_rate', 'display_name': 'Screen Refresh Rate', 'field_type': 'select', 'category': 'display',
             'options': ['60 Hz', '75 Hz', '120 Hz', '144 Hz', '165 Hz', '240 Hz', '360 Hz'], 'default_value': '144 Hz', 'order': 4},
            {'name': 'display_resolution', 'display_name': 'Display Resolution', 'field_type': 'select', 'category': 'display',
             'options': ['1280x720', '1600x900', '1920x1080', '2560x1440', '3440x1440', '3840x2160'], 'default_value': '1920x1080', 'order': 5},
            {'name': 'dynamic_resolution', 'display_name': 'Dynamic Resolution', 'field_type': 'toggle', 'category': 'display',
             'default_value': 'Off', 'order': 6},
            {'name': 'aspect_ratio', 'display_name': 'Aspect Ratio', 'field_type': 'select', 'category': 'display',
             'options': ['Automatic', '16:9', '16:10', '21:9', '32:9', '4:3'], 'default_value': 'Automatic', 'order': 7},
            {'name': 'vsync', 'display_name': 'V-Sync (Gameplay)', 'field_type': 'toggle', 'category': 'display',
             'default_value': 'Off', 'order': 8},
            {'name': 'vsync_menus', 'display_name': 'V-Sync (Menus)', 'field_type': 'toggle', 'category': 'display',
             'default_value': 'Off', 'order': 9},
            {'name': 'custom_framerate_limit', 'display_name': 'Custom Frame Rate Limit', 'field_type': 'select', 'category': 'display',
             'options': ['Unlimited', 'Custom'], 'default_value': 'Unlimited', 'order': 10},
            {'name': 'gameplay_custom_framerate', 'display_name': 'Gameplay Custom Frame Rate Limit', 'field_type': 'number', 'category': 'display',
             'min_value': 30, 'max_value': 1000, 'default_value': '250', 'order': 11},
            {'name': 'menu_custom_framerate', 'display_name': 'Menu Custom Frame Rate Limit', 'field_type': 'number', 'category': 'display',
             'min_value': 30, 'max_value': 1000, 'default_value': '250', 'order': 12},
            {'name': 'out_of_focus_framerate', 'display_name': 'Out of Focus Custom Frame Rate Limit', 'field_type': 'number', 'category': 'display',
             'min_value': 30, 'max_value': 1000, 'default_value': '30', 'order': 13},
            {'name': 'nvidia_reflex_low_latency', 'display_name': 'NVIDIA Reflex Low Latency', 'field_type': 'select', 'category': 'display',
             'options': ['Off', 'On', 'On + Boost'], 'default_value': 'On + Boost', 'order': 14},
            {'name': 'eco_mode_preset', 'display_name': 'Eco Mode Preset', 'field_type': 'toggle', 'category': 'display',
             'default_value': 'Off', 'order': 15},
            {'name': 'high_dynamic_range', 'display_name': 'High Dynamic Range (HDR)', 'field_type': 'toggle', 'category': 'display',
             'default_value': 'Off', 'order': 16},
            {'name': 'brightness', 'display_name': 'Brightness', 'field_type': 'number', 'category': 'display',
             'min_value': 0, 'max_value': 100, 'default_value': '50', 'order': 17},
            {'name': 'focused_mode', 'display_name': 'Focused Mode', 'field_type': 'toggle', 'category': 'display',
             'default_value': 'Off', 'order': 18},

            # === QUALITY TAB ===
            {'name': 'quality_preset', 'display_name': 'Quality Preset', 'field_type': 'select', 'category': 'graphics',
             'options': ['Minimum', 'Basic', 'Balanced', 'Competitive', 'Ultra', 'Extreme', 'Custom'], 'default_value': 'Balanced', 'order': 1},
            {'name': 'render_resolution', 'display_name': 'Render Resolution', 'field_type': 'select', 'category': 'graphics',
             'options': ['50', '55', '60', '65', '70', '75', '80', '85', '90', '95', '100'], 'default_value': '100', 'order': 2},
            {'name': 'upscaling_sharpening', 'display_name': 'Upscaling / Sharpening', 'field_type': 'select', 'category': 'graphics',
             'options': ['Off', 'FidelityFX CAS', 'NVIDIA DLSS', 'NVIDIA Image Scaling', 'AMD FSR 1.0', 'AMD FSR 2.1', 'AMD FSR 3.0', 'Intel XeSS'], 'default_value': 'FidelityFX CAS', 'order': 3},
            {'name': 'dlss_frame_generation', 'display_name': 'NVIDIA DLSS Frame Generation', 'field_type': 'toggle', 'category': 'graphics',
             'default_value': 'Off', 'order': 4},
            {'name': 'vram_scale_target', 'display_name': 'VRAM Scale Target', 'field_type': 'number', 'category': 'graphics',
             'min_value': 50, 'max_value': 100, 'default_value': '90', 'order': 5},
            {'name': 'variable_rate_shading', 'display_name': 'Variable Rate Shading', 'field_type': 'toggle', 'category': 'graphics',
             'default_value': 'On', 'order': 6},
            {'name': 'texture_resolution', 'display_name': 'Texture Resolution', 'field_type': 'select', 'category': 'graphics',
             'options': ['Very Low', 'Low', 'Normal', 'High', 'Ultra'], 'default_value': 'High', 'order': 7},
            {'name': 'texture_filter_anisotropic', 'display_name': 'Texture Filter Anisotropic', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Normal', 'High', 'Ultra'], 'default_value': 'High', 'order': 8},
            {'name': 'nearby_lod', 'display_name': 'Nearby Level of Detail', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Normal', 'High', 'Ultra'], 'default_value': 'High', 'order': 9},
            {'name': 'distant_lod', 'display_name': 'Distant Level of Detail', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Normal', 'High', 'Ultra'], 'default_value': 'High', 'order': 10},
            {'name': 'clutter_draw_distance', 'display_name': 'Clutter Draw Distance', 'field_type': 'select', 'category': 'graphics',
             'options': ['Short', 'Normal', 'Long', 'Ultra'], 'default_value': 'Normal', 'order': 11},
            {'name': 'particle_quality', 'display_name': 'Particle Quality', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Normal', 'High', 'Ultra'], 'default_value': 'High', 'order': 12},
            {'name': 'particle_quality_level', 'display_name': 'Particle Quality Level', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Normal', 'High', 'Ultra'], 'default_value': 'High', 'order': 13},
            {'name': 'bullet_impacts', 'display_name': 'Bullet Impacts & Sprays', 'field_type': 'toggle', 'category': 'graphics',
             'default_value': 'On', 'order': 14},
            {'name': 'persistent_effects', 'display_name': 'Persistent Effects', 'field_type': 'toggle', 'category': 'graphics',
             'default_value': 'Off', 'order': 15},
            {'name': 'shader_quality', 'display_name': 'Shader Quality', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Normal', 'High', 'Ultra'], 'default_value': 'High', 'order': 16},
            {'name': 'on_demand_texture_streaming', 'display_name': 'On-Demand Texture Streaming', 'field_type': 'toggle', 'category': 'graphics',
             'default_value': 'On', 'order': 17},
            {'name': 'local_texture_streaming', 'display_name': 'Local Texture Streaming Quality', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Normal', 'High', 'Ultra'], 'default_value': 'Normal', 'order': 18},

            # === QUALITY TAB - Shadow & Lighting ===
            {'name': 'shadow_map_resolution', 'display_name': 'Shadow Map Resolution', 'field_type': 'select', 'category': 'advanced',
             'options': ['Very Low', 'Low', 'Normal', 'High', 'Ultra', 'Extreme'], 'default_value': 'Normal', 'order': 1},
            {'name': 'screen_space_shadows', 'display_name': 'Screen Space Shadows', 'field_type': 'select', 'category': 'advanced',
             'options': ['Off', 'Low', 'High'], 'default_value': 'High', 'order': 2},
            {'name': 'spot_shadow_quality', 'display_name': 'Spot Shadow Quality', 'field_type': 'select', 'category': 'advanced',
             'options': ['Low', 'Normal', 'High', 'Ultra', 'Extreme'], 'default_value': 'High', 'order': 3},
            {'name': 'cache_spot_shadows', 'display_name': 'Cache Spot Shadows', 'field_type': 'toggle', 'category': 'advanced',
             'default_value': 'On', 'order': 4},
            {'name': 'cache_sun_shadows', 'display_name': 'Cache Sun Shadows', 'field_type': 'toggle', 'category': 'advanced',
             'default_value': 'On', 'order': 5},
            {'name': 'particle_lighting', 'display_name': 'Particle Lighting', 'field_type': 'select', 'category': 'advanced',
             'options': ['Low', 'Normal', 'High', 'Ultra'], 'default_value': 'Normal', 'order': 6},
            {'name': 'ambient_occlusion', 'display_name': 'Ambient Occlusion', 'field_type': 'select', 'category': 'advanced',
             'options': ['Off', 'GTAO', 'GTAO + RT AO (Ray Traced)'], 'default_value': 'GTAO', 'order': 7},
            {'name': 'screen_space_reflections', 'display_name': 'Screen Space Reflections', 'field_type': 'select', 'category': 'advanced',
             'options': ['Off', 'Normal', 'High'], 'default_value': 'Normal', 'order': 8},
            {'name': 'static_reflection_quality', 'display_name': 'Static Reflection Quality', 'field_type': 'select', 'category': 'advanced',
             'options': ['Low', 'Normal', 'High'], 'default_value': 'High', 'order': 9},
            {'name': 'tessellation', 'display_name': 'Tessellation', 'field_type': 'select', 'category': 'advanced',
             'options': ['Off', 'Near', 'All'], 'default_value': 'All', 'order': 10},
            {'name': 'terrain_memory', 'display_name': 'Terrain Memory', 'field_type': 'select', 'category': 'advanced',
             'options': ['Min', 'Low', 'Normal', 'High', 'Max'], 'default_value': 'High', 'order': 11},
            {'name': 'volumetric_quality', 'display_name': 'Volumetric Quality', 'field_type': 'select', 'category': 'advanced',
             'options': ['Low', 'Normal', 'High', 'Ultra'], 'default_value': 'Normal', 'order': 12},
            {'name': 'deferred_physics_quality', 'display_name': 'Deferred Physics Quality', 'field_type': 'toggle', 'category': 'advanced',
             'default_value': 'Off', 'order': 13},
            {'name': 'weather_grid_volumes', 'display_name': 'Weather Grid Volumes', 'field_type': 'select', 'category': 'advanced',
             'options': ['Off', 'Low', 'Normal', 'High', 'Ultra'], 'default_value': 'Normal', 'order': 14},
            {'name': 'water_caustics', 'display_name': 'Water Caustics', 'field_type': 'toggle', 'category': 'advanced',
             'default_value': 'On', 'order': 15},

            # === QUALITY TAB - Post Processing Effects ===
            {'name': 'anti_aliasing', 'display_name': 'Anti-Aliasing', 'field_type': 'select', 'category': 'postprocess',
             'options': ['Off', 'SMAA T2X', 'Filmic SMAA T2X'], 'default_value': 'Filmic SMAA T2X', 'order': 1},
            {'name': 'depth_of_field', 'display_name': 'Depth of Field', 'field_type': 'toggle', 'category': 'postprocess',
             'default_value': 'Off', 'order': 2},
            {'name': 'world_motion_blur', 'display_name': 'World Motion Blur', 'field_type': 'toggle', 'category': 'postprocess',
             'default_value': 'Off', 'order': 3},
            {'name': 'weapon_motion_blur', 'display_name': 'Weapon Motion Blur', 'field_type': 'toggle', 'category': 'postprocess',
             'default_value': 'Off', 'order': 4},
            {'name': 'film_grain', 'display_name': 'Film Grain', 'field_type': 'number', 'category': 'postprocess',
             'min_value': 0, 'max_value': 100, 'default_value': '0', 'order': 5},
            {'name': 'fidelityfx_cas_strength', 'display_name': 'FidelityFX CAS Strength', 'field_type': 'number', 'category': 'postprocess',
             'min_value': 0, 'max_value': 100, 'default_value': '50', 'order': 6},

            # === VIEW TAB ===
            {'name': 'field_of_view', 'display_name': 'Field of View', 'field_type': 'number', 'category': 'view',
             'min_value': 60, 'max_value': 120, 'default_value': '100', 'order': 1},
            {'name': 'ads_field_of_view', 'display_name': 'ADS Field of View', 'field_type': 'select', 'category': 'view',
             'options': ['Affected', 'Independent'], 'default_value': 'Affected', 'order': 2},
            {'name': 'weapon_field_of_view', 'display_name': 'Weapon Field of View', 'field_type': 'select', 'category': 'view',
             'options': ['Narrow', 'Default', 'Wide'], 'default_value': 'Wide', 'order': 3},
            {'name': 'vehicle_field_of_view', 'display_name': '3rd Person Vehicle Field of View', 'field_type': 'number', 'category': 'view',
             'min_value': 60, 'max_value': 120, 'default_value': '100', 'order': 4},
            {'name': 'world_camera_movement', 'display_name': 'World Camera Movement', 'field_type': 'select', 'category': 'view',
             'options': ['Least (50%)', 'Less (75%)', 'Default (100%)'], 'default_value': 'Least (50%)', 'order': 5},
            {'name': 'view_camera_movement', 'display_name': '1st Person Camera Movement', 'field_type': 'select', 'category': 'view',
             'options': ['Least (50%)', 'Less (75%)', 'Default (100%)'], 'default_value': 'Least (50%)', 'order': 6},
            {'name': 'third_person_camera_movement', 'display_name': '3rd Person Camera Movement', 'field_type': 'select', 'category': 'view',
             'options': ['Least (50%)', 'Less (75%)', 'Default (100%)'], 'default_value': 'Least (50%)', 'order': 7},
            {'name': 'vehicle_camera_movement', 'display_name': 'Vehicle Camera Movement', 'field_type': 'select', 'category': 'view',
             'options': ['Least (50%)', 'Less (75%)', 'Default (100%)'], 'default_value': 'Least (50%)', 'order': 8},
            {'name': 'inverted_flashbang', 'display_name': 'Inverted Flashbang', 'field_type': 'toggle', 'category': 'view',
             'default_value': 'On', 'order': 9},
        ]

        # ============================================================
        # BATTLEFIELD 2042 - Complete Graphics Settings
        # ============================================================
        battlefield_settings = [
            # === DISPLAY TAB ===
            {'name': 'fullscreen_mode', 'display_name': 'Fullscreen Mode', 'field_type': 'select', 'category': 'display',
             'options': ['Fullscreen', 'Borderless', 'Windowed'], 'default_value': 'Fullscreen', 'order': 1},
            {'name': 'fullscreen_resolution', 'display_name': 'Fullscreen Resolution', 'field_type': 'select', 'category': 'display',
             'options': ['1280x720', '1600x900', '1920x1080', '2560x1440', '3440x1440', '3840x2160'], 'default_value': '1920x1080', 'order': 2},
            {'name': 'refresh_rate', 'display_name': 'Refresh Rate', 'field_type': 'select', 'category': 'display',
             'options': ['60 Hz', '75 Hz', '120 Hz', '144 Hz', '165 Hz', '240 Hz', '360 Hz'], 'default_value': '144 Hz', 'order': 3},
            {'name': 'brightness', 'display_name': 'Brightness', 'field_type': 'number', 'category': 'display',
             'min_value': 0, 'max_value': 100, 'default_value': '50', 'order': 4},
            {'name': 'hdr', 'display_name': 'HDR', 'field_type': 'toggle', 'category': 'display',
             'default_value': 'Off', 'order': 5},
            {'name': 'nvidia_reflex_low_latency', 'display_name': 'NVIDIA Reflex Low Latency', 'field_type': 'select', 'category': 'display',
             'options': ['Off', 'On', 'On + Boost'], 'default_value': 'On + Boost', 'order': 6},
            {'name': 'vertical_sync', 'display_name': 'Vertical Sync', 'field_type': 'toggle', 'category': 'display',
             'default_value': 'Off', 'order': 7},
            {'name': 'framerate_limiter', 'display_name': 'Framerate Limiter', 'field_type': 'select', 'category': 'display',
             'options': ['Off', '30 FPS', '60 FPS', '120 FPS', '144 FPS', '165 FPS', '200 FPS', '240 FPS'], 'default_value': 'Off', 'order': 8},
            {'name': 'high_fidelity_objects_amount', 'display_name': 'High Fidelity Objects Amount', 'field_type': 'select', 'category': 'display',
             'options': ['Low', 'Medium', 'High', 'Ultra'], 'default_value': 'Medium', 'order': 9},
            {'name': 'ui_upscaling', 'display_name': 'UI Upscaling', 'field_type': 'toggle', 'category': 'display',
             'default_value': 'Off', 'order': 10},
            {'name': 'field_of_view', 'display_name': 'Field of View', 'field_type': 'number', 'category': 'display',
             'min_value': 55, 'max_value': 105, 'default_value': '90', 'order': 11},
            {'name': 'ads_field_of_view', 'display_name': 'ADS Field of View', 'field_type': 'toggle', 'category': 'display',
             'default_value': 'On', 'order': 12},
            {'name': 'vehicle_3p_fov', 'display_name': 'Vehicle 3rd Person Field of View', 'field_type': 'number', 'category': 'display',
             'min_value': 55, 'max_value': 105, 'default_value': '80', 'order': 13},
            {'name': 'motion_blur', 'display_name': 'Motion Blur', 'field_type': 'number', 'category': 'display',
             'min_value': 0, 'max_value': 100, 'default_value': '0', 'order': 14},
            {'name': 'chromatic_aberration', 'display_name': 'Chromatic Aberration', 'field_type': 'toggle', 'category': 'display',
             'default_value': 'Off', 'order': 15},
            {'name': 'film_grain', 'display_name': 'Film Grain', 'field_type': 'toggle', 'category': 'display',
             'default_value': 'Off', 'order': 16},
            {'name': 'vignette', 'display_name': 'Vignette', 'field_type': 'toggle', 'category': 'display',
             'default_value': 'Off', 'order': 17},
            {'name': 'lens_distortion', 'display_name': 'Lens Distortion', 'field_type': 'toggle', 'category': 'display',
             'default_value': 'Off', 'order': 18},

            # === GRAPHICS QUALITY TAB ===
            {'name': 'graphics_quality', 'display_name': 'Graphics Quality', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Medium', 'High', 'Ultra', 'Custom'], 'default_value': 'High', 'order': 1},
            {'name': 'texture_quality', 'display_name': 'Texture Quality', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Medium', 'High', 'Ultra'], 'default_value': 'High', 'order': 2},
            {'name': 'texture_filtering', 'display_name': 'Texture Filtering', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Medium', 'High', 'Ultra'], 'default_value': 'Ultra', 'order': 3},
            {'name': 'lighting_quality', 'display_name': 'Lighting Quality', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Medium', 'High', 'Ultra'], 'default_value': 'High', 'order': 4},
            {'name': 'effects_quality', 'display_name': 'Effects Quality', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Medium', 'High', 'Ultra'], 'default_value': 'High', 'order': 5},
            {'name': 'post_process_quality', 'display_name': 'Post Process Quality', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Medium', 'High', 'Ultra'], 'default_value': 'High', 'order': 6},
            {'name': 'mesh_quality', 'display_name': 'Mesh Quality', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Medium', 'High', 'Ultra'], 'default_value': 'High', 'order': 7},
            {'name': 'undergrowth_quality', 'display_name': 'Undergrowth Quality', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Medium', 'High', 'Ultra'], 'default_value': 'Medium', 'order': 8},
            {'name': 'terrain_quality', 'display_name': 'Terrain Quality', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Medium', 'High', 'Ultra'], 'default_value': 'High', 'order': 9},
            {'name': 'anti_aliasing_post', 'display_name': 'Anti-Aliasing Post', 'field_type': 'select', 'category': 'graphics',
             'options': ['Off', 'TAA Low', 'TAA High'], 'default_value': 'TAA High', 'order': 10},
            {'name': 'ambient_occlusion', 'display_name': 'Ambient Occlusion', 'field_type': 'select', 'category': 'graphics',
             'options': ['Off', 'SSAO', 'HBAO'], 'default_value': 'HBAO', 'order': 11},

            # === ADVANCED TAB ===
            {'name': 'dlss', 'display_name': 'DLSS', 'field_type': 'select', 'category': 'advanced',
             'options': ['Off', 'Auto', 'Quality', 'Balanced', 'Performance', 'Ultra Performance'], 'default_value': 'Off', 'order': 1},
            {'name': 'dlss_sharpness', 'display_name': 'DLSS Sharpness', 'field_type': 'number', 'category': 'advanced',
             'min_value': 0, 'max_value': 100, 'default_value': '50', 'order': 2},
            {'name': 'dlss_frame_generation', 'display_name': 'DLSS Frame Generation', 'field_type': 'toggle', 'category': 'advanced',
             'default_value': 'Off', 'order': 3},
            {'name': 'fsr_2', 'display_name': 'FSR 2', 'field_type': 'select', 'category': 'advanced',
             'options': ['Off', 'Quality', 'Balanced', 'Performance', 'Ultra Performance'], 'default_value': 'Off', 'order': 4},
            {'name': 'fsr_2_sharpness', 'display_name': 'FSR 2 Sharpness', 'field_type': 'number', 'category': 'advanced',
             'min_value': 0, 'max_value': 100, 'default_value': '50', 'order': 5},
            {'name': 'resolution_scale', 'display_name': 'Resolution Scale', 'field_type': 'number', 'category': 'advanced',
             'min_value': 25, 'max_value': 200, 'default_value': '100', 'order': 6},
            {'name': 'dx12_enabled', 'display_name': 'DirectX 12 Enabled', 'field_type': 'toggle', 'category': 'advanced',
             'default_value': 'On', 'order': 7},
            {'name': 'future_frame_rendering', 'display_name': 'Future Frame Rendering', 'field_type': 'toggle', 'category': 'advanced',
             'default_value': 'On', 'order': 8},
            {'name': 'gpu_memory_restriction', 'display_name': 'GPU Memory Restriction', 'field_type': 'toggle', 'category': 'advanced',
             'default_value': 'Off', 'order': 9},
            {'name': 'ray_traced_ambient_occlusion', 'display_name': 'Ray Traced Ambient Occlusion', 'field_type': 'toggle', 'category': 'advanced',
             'default_value': 'Off', 'order': 10},
            {'name': 'ray_traced_reflections', 'display_name': 'Ray Traced Reflections', 'field_type': 'toggle', 'category': 'advanced',
             'default_value': 'Off', 'order': 11},
        ]

        # ============================================================
        # ARC RAIDERS - Complete Graphics Settings
        # ============================================================
        arc_raiders_settings = [
            # === DISPLAY TAB ===
            {'name': 'window_mode', 'display_name': 'Window Mode', 'field_type': 'select', 'category': 'display',
             'options': ['Fullscreen', 'Windowed Fullscreen', 'Windowed'], 'default_value': 'Fullscreen', 'order': 1},
            {'name': 'resolution', 'display_name': 'Resolution', 'field_type': 'select', 'category': 'display',
             'options': ['1280x720', '1600x900', '1920x1080', '2560x1440', '3440x1440', '3840x2160'], 'default_value': '1920x1080', 'order': 2},
            {'name': 'resolution_scale', 'display_name': 'Resolution Scale', 'field_type': 'number', 'category': 'display',
             'min_value': 25, 'max_value': 100, 'default_value': '100', 'order': 3},
            {'name': 'vsync', 'display_name': 'VSync', 'field_type': 'toggle', 'category': 'display',
             'default_value': 'Off', 'order': 4},
            {'name': 'frame_rate_limit', 'display_name': 'Frame Rate Limit', 'field_type': 'select', 'category': 'display',
             'options': ['Unlimited', '30', '60', '90', '120', '144', '165', '240'], 'default_value': 'Unlimited', 'order': 5},
            {'name': 'nvidia_reflex', 'display_name': 'NVIDIA Reflex Low Latency', 'field_type': 'select', 'category': 'display',
             'options': ['Off', 'On', 'On + Boost'], 'default_value': 'On + Boost', 'order': 6},
            {'name': 'brightness', 'display_name': 'Brightness', 'field_type': 'number', 'category': 'display',
             'min_value': 0, 'max_value': 100, 'default_value': '50', 'order': 7},
            {'name': 'gamma', 'display_name': 'Gamma', 'field_type': 'number', 'category': 'display',
             'min_value': 0, 'max_value': 100, 'default_value': '50', 'order': 8},
            {'name': 'hdr_mode', 'display_name': 'HDR Mode', 'field_type': 'toggle', 'category': 'display',
             'default_value': 'Off', 'order': 9},
            {'name': 'hdr_brightness', 'display_name': 'HDR Brightness', 'field_type': 'number', 'category': 'display',
             'min_value': 0, 'max_value': 100, 'default_value': '50', 'order': 10},
            {'name': 'field_of_view', 'display_name': 'Field of View', 'field_type': 'number', 'category': 'display',
             'min_value': 70, 'max_value': 120, 'default_value': '90', 'order': 11},

            # === GRAPHICS QUALITY TAB ===
            {'name': 'overall_quality', 'display_name': 'Overall Quality', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Medium', 'High', 'Epic', 'Cinematic', 'Custom'], 'default_value': 'High', 'order': 1},
            {'name': 'view_distance', 'display_name': 'View Distance', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Medium', 'High', 'Epic', 'Cinematic'], 'default_value': 'High', 'order': 2},
            {'name': 'anti_aliasing', 'display_name': 'Anti-Aliasing', 'field_type': 'select', 'category': 'graphics',
             'options': ['Off', 'Low', 'Medium', 'High', 'Epic'], 'default_value': 'High', 'order': 3},
            {'name': 'post_processing', 'display_name': 'Post Processing', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Medium', 'High', 'Epic', 'Cinematic'], 'default_value': 'High', 'order': 4},
            {'name': 'shadows', 'display_name': 'Shadows', 'field_type': 'select', 'category': 'graphics',
             'options': ['Off', 'Low', 'Medium', 'High', 'Epic', 'Cinematic'], 'default_value': 'High', 'order': 5},
            {'name': 'textures', 'display_name': 'Textures', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Medium', 'High', 'Epic', 'Cinematic'], 'default_value': 'High', 'order': 6},
            {'name': 'effects', 'display_name': 'Effects', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Medium', 'High', 'Epic', 'Cinematic'], 'default_value': 'High', 'order': 7},
            {'name': 'foliage', 'display_name': 'Foliage', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Medium', 'High', 'Epic', 'Cinematic'], 'default_value': 'Medium', 'order': 8},
            {'name': 'shading', 'display_name': 'Shading Quality', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Medium', 'High', 'Epic', 'Cinematic'], 'default_value': 'High', 'order': 9},
            {'name': 'global_illumination', 'display_name': 'Global Illumination', 'field_type': 'select', 'category': 'graphics',
             'options': ['Low', 'Medium', 'High', 'Epic', 'Lumen'], 'default_value': 'High', 'order': 10},
            {'name': 'reflections', 'display_name': 'Reflections', 'field_type': 'select', 'category': 'graphics',
             'options': ['Off', 'Screen Space', 'High', 'Epic', 'Lumen'], 'default_value': 'High', 'order': 11},

            # === ADVANCED TAB ===
            {'name': 'upscaling_method', 'display_name': 'Upscaling Method', 'field_type': 'select', 'category': 'advanced',
             'options': ['Off', 'NVIDIA DLSS', 'AMD FSR 2.0', 'AMD FSR 3.0', 'Intel XeSS', 'Unreal TSR'], 'default_value': 'Off', 'order': 1},
            {'name': 'upscaling_quality', 'display_name': 'Upscaling Quality', 'field_type': 'select', 'category': 'advanced',
             'options': ['Ultra Performance', 'Performance', 'Balanced', 'Quality', 'Ultra Quality'], 'default_value': 'Quality', 'order': 2},
            {'name': 'dlss_frame_generation', 'display_name': 'DLSS Frame Generation', 'field_type': 'toggle', 'category': 'advanced',
             'default_value': 'Off', 'order': 3},
            {'name': 'ray_tracing', 'display_name': 'Ray Tracing', 'field_type': 'toggle', 'category': 'advanced',
             'default_value': 'Off', 'order': 4},
            {'name': 'ray_traced_shadows', 'display_name': 'Ray Traced Shadows', 'field_type': 'toggle', 'category': 'advanced',
             'default_value': 'Off', 'order': 5},
            {'name': 'ray_traced_reflections', 'display_name': 'Ray Traced Reflections', 'field_type': 'toggle', 'category': 'advanced',
             'default_value': 'Off', 'order': 6},
            {'name': 'ray_traced_global_illumination', 'display_name': 'Ray Traced Global Illumination', 'field_type': 'toggle', 'category': 'advanced',
             'default_value': 'Off', 'order': 7},
            {'name': 'motion_blur', 'display_name': 'Motion Blur', 'field_type': 'select', 'category': 'advanced',
             'options': ['Off', 'Low', 'Medium', 'High'], 'default_value': 'Off', 'order': 8},
            {'name': 'depth_of_field', 'display_name': 'Depth of Field', 'field_type': 'toggle', 'category': 'advanced',
             'default_value': 'Off', 'order': 9},
            {'name': 'bloom', 'display_name': 'Bloom', 'field_type': 'toggle', 'category': 'advanced',
             'default_value': 'On', 'order': 10},
            {'name': 'lens_flare', 'display_name': 'Lens Flare', 'field_type': 'toggle', 'category': 'advanced',
             'default_value': 'Off', 'order': 11},
            {'name': 'chromatic_aberration', 'display_name': 'Chromatic Aberration', 'field_type': 'toggle', 'category': 'advanced',
             'default_value': 'Off', 'order': 12},
            {'name': 'film_grain', 'display_name': 'Film Grain', 'field_type': 'toggle', 'category': 'advanced',
             'default_value': 'Off', 'order': 13},
            {'name': 'vignette', 'display_name': 'Vignette', 'field_type': 'toggle', 'category': 'advanced',
             'default_value': 'Off', 'order': 14},

            # === VIEW TAB ===
            {'name': 'camera_shake', 'display_name': 'Camera Shake', 'field_type': 'number', 'category': 'view',
             'min_value': 0, 'max_value': 100, 'default_value': '50', 'order': 1},
            {'name': 'head_bob', 'display_name': 'Head Bob', 'field_type': 'number', 'category': 'view',
             'min_value': 0, 'max_value': 100, 'default_value': '50', 'order': 2},
            {'name': 'vehicle_camera_shake', 'display_name': 'Vehicle Camera Shake', 'field_type': 'number', 'category': 'view',
             'min_value': 0, 'max_value': 100, 'default_value': '50', 'order': 3},
        ]

        game_settings_map = {
            'Call of Duty': cod_settings,
            'Battlefield': battlefield_settings,
            'Arc Raiders': arc_raiders_settings,
        }

        for game_name, settings in game_settings_map.items():
            # Find game by partial match
            game = Game.objects.filter(name__icontains=game_name.split()[0]).first()
            if not game:
                self.stdout.write(self.style.WARNING(f'Game "{game_name}" not found, creating it...'))
                game = Game.objects.create(name=game_name, slug=game_name.lower().replace(' ', '-'))

            # Clear existing settings for this game
            deleted_count, _ = GameSettingDefinition.objects.filter(game=game).delete()
            if deleted_count > 0:
                self.stdout.write(f'Cleared {deleted_count} existing settings for {game.name}')

            # Create new settings
            for setting in settings:
                GameSettingDefinition.objects.create(
                    game=game,
                    name=setting['name'],
                    display_name=setting['display_name'],
                    field_type=setting['field_type'],
                    category=setting['category'],
                    options=setting.get('options'),
                    min_value=setting.get('min_value'),
                    max_value=setting.get('max_value'),
                    default_value=setting.get('default_value'),
                    order=setting['order'],
                )
            
            self.stdout.write(self.style.SUCCESS(f'Created {len(settings)} settings for {game.name}'))

        self.stdout.write(self.style.SUCCESS('Successfully seeded all game settings!'))
