# Generated by Django 6.0.1 on 2026-01-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_game_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='weapons/'),
        ),
    ]
