# Generated by Django 6.0.1 on 2026-01-17 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_weapon_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Profile name (e.g., "Competitive Settings")', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('values', models.JSONField(default=dict, help_text='Setting values as {setting_name: value}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting_profiles', to='core.game')),
            ],
            options={
                'ordering': ['game', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GameSettingDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name (e.g., texture_quality)', max_length=100)),
                ('display_name', models.CharField(help_text='Display name (e.g., Texture Quality)', max_length=100)),
                ('field_type', models.CharField(choices=[('select', 'Dropdown Select'), ('number', 'Number'), ('toggle', 'On/Off Toggle'), ('text', 'Text Input')], default='select', max_length=20)),
                ('category', models.CharField(choices=[('display', 'Display'), ('graphics', 'Graphics Quality'), ('advanced', 'Advanced Graphics'), ('view', 'View Settings'), ('audio', 'Audio'), ('controls', 'Controls')], default='graphics', max_length=50)),
                ('options', models.JSONField(blank=True, help_text='For select fields: ["Low", "Medium", "High", "Ultra"]', null=True)),
                ('min_value', models.IntegerField(blank=True, help_text='For number fields', null=True)),
                ('max_value', models.IntegerField(blank=True, help_text='For number fields', null=True)),
                ('default_value', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order within category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting_definitions', to='core.game')),
            ],
            options={
                'ordering': ['game', 'category', 'order', 'display_name'],
                'unique_together': {('game', 'name')},
            },
        ),
    ]
