# Generated by Django 6.0.1 on 2026-01-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gamesettingprofile_gamesettingdefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettingprofile',
            name='graphic_card',
            field=models.CharField(blank=True, help_text='e.g., NVIDIA RTX 4080', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='gamesettingprofile',
            name='processor_type',
            field=models.CharField(blank=True, help_text='e.g., Intel Core i7-13700K', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='gamesettingprofile',
            name='ram',
            field=models.CharField(blank=True, help_text='e.g., 32GB DDR5', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettingdefinition',
            name='category',
            field=models.CharField(choices=[('display', 'Display'), ('graphics', 'Graphics Quality'), ('advanced', 'Advanced Graphics'), ('postprocess', 'Post Processing'), ('view', 'View Settings'), ('audio', 'Audio'), ('controls', 'Controls')], default='graphics', max_length=50),
        ),
    ]
