# Generated by Django 6.0.1 on 2026-01-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_attachmenttype_alter_attachment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Only active weapons are shown on the site'),
        ),
    ]
