# Generated by Django 6.0.1 on 2026-01-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_change_game_is_active_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('shooter', 'Shooter'), ('racing', 'Racing'), ('sports', 'Sports'), ('rpg', 'RPG'), ('strategy', 'Strategy'), ('simulation', 'Simulation'), ('adventure', 'Adventure'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
