# Generated by Django 6.0.1 on 2026-01-18 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('reason', models.CharField(choices=[('auto', 'Automatic - Too Many Failures'), ('manual', 'Manual - Admin Action'), ('brute_force', 'Brute Force Attack'), ('ddos', 'DDoS Attack'), ('suspicious', 'Suspicious Activity')], default='auto', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('is_permanent', models.BooleanField(default=False)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_ips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP Block',
                'verbose_name_plural': 'IP Blocks',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('request_count', models.IntegerField(default=0)),
                ('window_start', models.DateTimeField(auto_now_add=True)),
                ('last_request', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', 'endpoint', '-window_start'], name='core_rateli_ip_addr_9b6b10_idx')],
                'unique_together': {('ip_address', 'endpoint', 'window_start')},
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_fail', 'Failed Login'), ('login_success', 'Successful Login'), ('register_attempt', 'Registration Attempt'), ('register_success', 'Successful Registration'), ('rate_limit', 'Rate Limit Exceeded'), ('ip_blocked', 'IP Blocked'), ('suspicious', 'Suspicious Activity'), ('brute_force', 'Brute Force Detected'), ('ddos', 'Potential DDoS')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=10)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'event_type'], name='core_securi_timesta_caaa4f_idx'), models.Index(fields=['ip_address', '-timestamp'], name='core_securi_ip_addr_bc5740_idx')],
            },
        ),
    ]
