# Generated by Django 6.0.1 on 2026-01-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ipblock_ratelimittracker_securityevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main banner title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle or description', max_length=300, null=True)),
                ('banner_type', models.CharField(choices=[('event', 'Event'), ('announcement', 'Announcement'), ('maintenance', 'Maintenance'), ('update', 'Update'), ('stream', 'Live Stream')], default='event', max_length=20)),
                ('color_scheme', models.CharField(choices=[('blue', 'Blue'), ('purple', 'Purple'), ('green', 'Green'), ('red', 'Red'), ('orange', 'Orange'), ('pink', 'Pink'), ('gradient', 'Gradient')], default='blue', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Optional banner image', null=True, upload_to='banners/')),
                ('event_date', models.DateTimeField(blank=True, help_text='Event date/time for countdown', null=True)),
                ('show_countdown', models.BooleanField(default=True, help_text='Show countdown timer')),
                ('link_url', models.URLField(blank=True, help_text='Optional link when clicking the banner', null=True)),
                ('link_text', models.CharField(blank=True, help_text='Link button text', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Show this banner')),
                ('is_dismissible', models.BooleanField(default=True, help_text='Allow users to close the banner')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority shows first')),
                ('start_date', models.DateTimeField(blank=True, help_text='When to start showing the banner', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When to stop showing the banner', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Banner',
                'verbose_name_plural': 'Event Banners',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
