# Generated by Django 6.0.1 on 2026-01-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_event_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Main brand color (hex)', max_length=7)),
                ('primary_hover', models.CharField(default='#2563EB', help_text='Primary hover state (hex)', max_length=7)),
                ('primary_text', models.CharField(default='#FFFFFF', help_text='Text on primary background (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#8B5CF6', help_text='Secondary accent color (hex)', max_length=7)),
                ('secondary_hover', models.CharField(default='#7C3AED', max_length=7)),
                ('secondary_text', models.CharField(default='#FFFFFF', max_length=7)),
                ('bg_primary', models.CharField(default='#0F172A', help_text='Main background', max_length=7)),
                ('bg_secondary', models.CharField(default='#1E293B', help_text='Card/panel background', max_length=7)),
                ('bg_tertiary', models.CharField(default='#334155', help_text='Hover/elevated background', max_length=7)),
                ('text_primary', models.CharField(default='#F1F5F9', help_text='Main text color', max_length=7)),
                ('text_secondary', models.CharField(default='#94A3B8', help_text='Muted text', max_length=7)),
                ('text_tertiary', models.CharField(default='#64748B', help_text='Very muted text', max_length=7)),
                ('border_color', models.CharField(default='#334155', max_length=7)),
                ('border_hover', models.CharField(default='#475569', max_length=7)),
                ('success_color', models.CharField(default='#10B981', max_length=7)),
                ('warning_color', models.CharField(default='#F59E0B', max_length=7)),
                ('error_color', models.CharField(default='#EF4444', max_length=7)),
                ('info_color', models.CharField(default='#3B82F6', max_length=7)),
                ('font_family_base', models.CharField(default='-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif', max_length=200)),
                ('font_family_heading', models.CharField(default='-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif', max_length=200)),
                ('font_family_mono', models.CharField(default='ui-monospace, Menlo, Monaco, "Cascadia Mono", "Courier New", monospace', max_length=200)),
                ('font_size_base', models.CharField(default='16px', max_length=10)),
                ('font_size_sm', models.CharField(default='14px', max_length=10)),
                ('font_size_lg', models.CharField(default='18px', max_length=10)),
                ('font_size_xl', models.CharField(default='20px', max_length=10)),
                ('spacing_unit', models.CharField(default='4px', help_text='Base spacing unit', max_length=10)),
                ('border_radius_sm', models.CharField(default='4px', max_length=10)),
                ('border_radius_md', models.CharField(default='8px', max_length=10)),
                ('border_radius_lg', models.CharField(default='12px', max_length=10)),
                ('border_radius_xl', models.CharField(default='16px', max_length=10)),
                ('navbar_bg', models.CharField(default='#1E293B', max_length=7)),
                ('navbar_text', models.CharField(default='#F1F5F9', max_length=7)),
                ('sidebar_bg', models.CharField(default='#1E293B', max_length=7)),
                ('sidebar_text', models.CharField(default='#F1F5F9', max_length=7)),
                ('button_radius', models.CharField(default='8px', max_length=10)),
                ('input_radius', models.CharField(default='6px', max_length=10)),
                ('card_radius', models.CharField(default='12px', max_length=10)),
                ('shadow_sm', models.CharField(default='0 1px 2px 0 rgb(0 0 0 / 0.05)', max_length=100)),
                ('shadow_md', models.CharField(default='0 4px 6px -1px rgb(0 0 0 / 0.1)', max_length=100)),
                ('shadow_lg', models.CharField(default='0 10px 15px -3px rgb(0 0 0 / 0.1)', max_length=100)),
                ('custom_css', models.TextField(blank=True, help_text='Additional custom CSS')),
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
    ]
