# Generated by Django 6.0.1 on 2026-01-18 20:28

import forum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_add_forum_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrank',
            name='image',
            field=models.ImageField(blank=True, help_text='Custom rank image (will be resized to 64x64)', null=True, upload_to=forum.models.rank_image_path),
        ),
    ]
